### ISSUE TITLE
Difference between public and private link is not clear

### ISSUE THREAD

**Issue by ghost** [jeanbaptistevilain/module-test-puppeteer#12]

**Comment by ValentinFLGT** [comment]
Hi John, 

Thank for your feedback, effectively nothing change on the page when you hit the public or secret button.
This might be a bug, i'll report your feedback to our development team !

![image](https://user-images.githubusercontent.com/58422968/91557374-a855fc00-e934-11ea-9afd-a4a4b806ebfb.png)

**Comment by jeanbaptistevilain** [comment]
What's the point of having both buttons then ?

**Comment by ghost** [comment]
Hi John,

When you shorten a URL with the secret button enabled you're URL will be almost impossible to discover. It's a security feature.

![image](https://user-images.githubusercontent.com/58422968/91563030-7c3f7880-e93e-11ea-85e2-35018f4b6435.png)

https://docs.polrproject.org/en/latest/developer-guide/api/#apiv2actionshorten

**Comment by jeanbaptistevilain** [comment]
Oh it makes sense now, thanks ! (who's John by the way ?)
