### ISSUE TITLE
API's sending random 403 

### ISSUE THREAD

**Issue by ghost** [jeanbaptistevilain/module-test-puppeteer#9]
Hi John ! 

I'm sorry to hear you're having troubles using our API. Can you please send me the endpoints you're trying to reach when you have these 403 errors ?

Valentin.

**Comment by jeanbaptistevilain** [comment]
Hi,
I'm just trying to call the url shortening service via http://example.com/api/v2/action/shorten?key=API_KEY_HERE&url=https://google.com&custom_ending=CUSTOM_ENDING&is_secret=false

**Comment by ghost** [comment]
Hi John,

It looks like you exceeded your quota.

![image](https://user-images.githubusercontent.com/58422968/91561641-3e415500-e93c-11ea-9e56-3fd5c3f2e05f.png)
https://docs.polrproject.org/en/latest/developer-guide/api/#http-403-forbidden

**Comment by jeanbaptistevilain** [comment]
My bad then, thanks for the quick update !
